Product.create!(title: 'Rocketman Gem')
Product.create!(title: 'Dirtclod Gem')
Product.create!(title: 'RoR Gem')
Product.create!(title: 'Blue Flame Gem')
Product.create!(title: 'Granny Gem')
Product.create!(title: 'Anti-Gem')
